#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 31, 2020 07:17:33 PM +06  platform: Windows NT
import os
import pickle
import sys
import pyAesCrypt
from PIL import ImageTk

import FirstPage
import Lock
import tkinter as tk
from tkinter import messagebox, filedialog
import tkinter.ttk as ttk


def start(x, facelock=False):
    '''Starting point when module is the main routine.'''
    global val, w, root, dict, FACELOCK
    FACELOCK = facelock
    dict = x
    root = tk.Tk()
    top = Toplevel1(root)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    return (w, top)


def destroy_Toplevel1():
    global root
    root.destroy()
    root = None


class Toplevel1:
    def saveDict(self):
        global dict
        f = open("Storage/Info.pkl", "wb")
        pickle.dump(dict, f)
        f.close()

    def setLock(self):
        Lock.capture(True)
        global dict
        dict['facelock'] = 1
        self.saveDict()
        self.addFacelock()
        self.addLabel()

    def removeLock(self):
        MsgBox = messagebox.askquestion('Warning!', 'Removing Facelock! Are you sure?',
                                        icon='warning')
        if MsgBox == 'yes':
            global dict
            dict['facelock'] = None
            self.saveDict()
            self.addFacelock()
            self.addLabel()

    def unlock(self, file, original):
        MsgBox = messagebox.askquestion('Warning!', 'Unlocking File! Are you sure?',
                                        icon='warning')
        if MsgBox == 'yes':
            ext = file.split('.')[-1]
            filename = filedialog.asksaveasfilename(initialdir=original, initialfile=file ,title='Save '+file, defaultextension='.'+ext,
                                                    filetypes=((ext + " files", "*." + ext), ("all files", "*.*")))
            if len(filename) > 2:
                bufferSize = 64 * 1024
                password = "ProjectSDPbyOpu"
                filename=filename
                pyAesCrypt.decryptFile('Storage/' + file + ".aes", filename, password, bufferSize)
                global dict
                del dict[file]
                self.saveDict()
                self.fileList()

    def addFacelock(self):
        self.facelock = tk.Button(self.Frame1)
        self.facelock.place(relx=0.053, rely=0.053, height=225, width=225)
        self.facelock.configure(activebackground="#ececec")
        self.facelock.configure(activeforeground="#000000")
        self.facelock.configure(background="#d9d9d9")
        self.facelock.configure(disabledforeground="#a3a3a3")
        self.facelock.configure(foreground="#000000")
        self.facelock.configure(highlightbackground="#d9d9d9")
        self.facelock.configure(highlightcolor="black")
        self.facelock.configure(pady="0")
        if dict['facelock'] == None:
            photo_location = r"Images\notfacelock.png"
            self.facelock.configure(command=self.setLock)
        else:
            photo_location = r"Images\facelock.png"
            self.facelock.configure(command=self.removeLock)
        global _img0
        print(photo_location)
        _img0 = ImageTk.PhotoImage(file=photo_location)
        self.facelock.configure(image=_img0)

    def addLabel(self):
        self.label = tk.Label(self.Frame1)
        self.label.place(relx=0.01, rely=0.700, height=70, width=262)
        self.label.configure(activebackground="#f9f9f9")
        self.label.configure(activeforeground="black")
        self.label.configure(background="#d9d9d9")
        self.label.configure(disabledforeground="#a3a3a3")
        self.label.configure(foreground="#000000")
        self.label.configure(highlightbackground="#d9d9d9")
        self.label.configure(highlightcolor="black")
        global FACELOCK
        if FACELOCK and dict['facelock'] is not None:
            self.label.configure(text='FaceLock Activated\nUnlocked with Facelock')
        elif not FACELOCK and dict['facelock'] is not None:
            self.label.configure(text='Facelock Activated')
        else:
            self.label.configure(text='Facelock Deactivated')

    def fileList(self):
        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.369, rely=0.053, relheight=0.895, relwidth=0.586)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")

        canvas = tk.Canvas(self.Frame2)
        scroll_y = tk.Scrollbar(self.Frame2, orient="vertical", command=canvas.yview)

        frame = tk.Frame(canvas)
        buttons = [tk.Button()] * len(dict)
        names = [tk.Label()] * len(dict)
        names[0] = tk.Label(frame, text='File Name', fg='blue', anchor='w')
        names[0].grid(row=0, column=1, padx=2, pady=3)
        i = 1
        for key in dict:
            if key == 'username' or key == 'facelock' or key == 'password':
                continue
            if len(key) > 30:
                name = key.split(' ')[0] + '.' + key.split('.')[-1]
            else:
                name = key
            names[i] = tk.Label(frame, text=name, anchor='w')
            names[i].grid(row=i, column=1, padx=2, pady=3)
            buttons[i] = tk.Button(frame, text='Unlock', anchor='e',
                                   command=lambda f=key, o=dict[key]: self.unlock(f, o))
            buttons[i].grid(row=i, column=3, padx=20, pady=3)
            i = i + 1
        canvas.create_window(0, 0, anchor='nw', window=frame)
        canvas.update_idletasks()
        canvas.configure(scrollregion=canvas.bbox('all'),
                         yscrollcommand=scroll_y.set)
        canvas.pack(fill='both', expand=True, side='left')
        scroll_y.pack(fill='y', side='right')

    def lockFile(self):
        filename = filedialog.askopenfilename(initialdir="/", title="Select file",
                                              filetypes=(("all files", "*.*"), ("jpeg files", "*.jpg")))
        if len(filename) > 2:
            bufferSize = 64 * 1024
            password = "ProjectSDPbyOpu"
            # encrypt
            fName = filename.split('/')[-1]
            pyAesCrypt.encryptFile(filename, 'Storage/' + fName + '.aes', password, bufferSize)
            dict[fName] = filename
            self.saveDict()
            self.fileList()
        return

    def __init__(self, top=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("759x564+305+111")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1, 1)
        top.title("Locker")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=1.0)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ffffff")

        self.addFacelock()

        self.lock = tk.Button(self.Frame1)
        self.lock.place(relx=0.1, rely=0.532, height=54, width=147)
        self.lock.configure(activebackground="#ececec")
        self.lock.configure(activeforeground="#000000")
        self.lock.configure(background="#d9d9d9")
        self.lock.configure(command=self.lockFile)
        self.lock.configure(disabledforeground="#a3a3a3")
        self.lock.configure(foreground="#000000")
        self.lock.configure(highlightbackground="#d9d9d9")
        self.lock.configure(highlightcolor="black")
        self.lock.configure(pady="0")
        self.lock.configure(text='''Lock File''')

        self.addLabel()

        self.fileList()

        self.exit = tk.Button(self.Frame1, command=destroy_Toplevel1)
        self.exit.place(relx=0.15, rely=0.922, height=30, width=50)
        self.exit.configure(activebackground="#ececec")
        self.exit.configure(activeforeground="#000000")
        self.exit.configure(background="#d9d9d9")
        self.exit.configure(disabledforeground="#a3a3a3")
        self.exit.configure(foreground="#000000")
        self.exit.configure(highlightbackground="#d9d9d9")
        self.exit.configure(highlightcolor="black")
        self.exit.configure(pady="0")
        self.exit.configure(text='''Exit''')
